export const ADDRESSES_ERROR_CODES = {
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  INVALID_STREET: 'INVALID_STREET',
  INVALID_NUMBER: 'INVALID_NUMBER',
  INVALID_NEIGHBORHOOD: 'INVALID_NEIGHBORHOOD',
  INVALID_CITY: 'INVALID_CITY',
  INVALID_STATE: 'INVALID_STATE',
  INVALID_ZIP_CODE: 'INVALID_ZIP_CODE',
} as const;
