export const COMMON_ERRORS = {
  INVALID_NAME: 'INVALID_NAME',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  NAME_LIMIT_EXCEEDED: 'NAME_LIMIT_EXCEEDED',
  NAME_REQUIRED: 'NAME_REQUIRED',
} as const;
