export const SYSTEM_ERRORS = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_SEARCH: 'INVALID_SEARCH',
  INVALID_IS_FAVORITE: 'INVALID_IS_FAVORITE',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_PAGE: 'INVALID_PAGE',
  INVALID_PER_PAGE: 'INVALID_PER_PAGE',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  FILE_REQUIRED: 'FILE_REQUIRED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
} as const;
