export const TAG_ERRORS = {
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_ALREADY_EXISTS: 'TAG_ALREADY_EXISTS',
  TAG_LIMIT_EXCEEDED: 'TAG_LIMIT_EXCEEDED',
  INVALID_COLOR: 'INVALID_COLOR',
  COLOR_REQUIRED: 'COLOR_REQUIRED',
} as const;
