export const USER_ERRORS = {
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORDS_MUST_DIFFERENT: 'PASSWORDS_MUST_DIFFERENT',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_VERIFIED: 'USER_ALREADY_VERIFIED',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
} as const;
